services:
  postgres-primary:
    image: postgres:16
    environment:
      POSTGRES_USER: peak
      POSTGRES_PASSWORD: peak
      POSTGRES_DB: peak
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -U peak -d peak]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-primary-data:
